### ISSUE TITLE
ValueError: read length must be non-negative or -1

### ISSUE THREAD

**Issue by Crafty-The-Fox** [maxwell-nc/Uexp2Awb#1]
not sure what to do. it throws this error when trying to use it. UE4 version 4.19.

```
find:72836
end:-1
Traceback (most recent call last):
  File "C:\Users\xxx\Downloads\xxx\Voice\uexp2awb.py", line 45, in <module>
    splitUexp(root,file)
  File "C:\Users\xxx\Downloads\xxx\Voice\uexp2awb.py", line 37, in splitUexp
    copypart(inPath,outPath,afs2pos,endPos-afs2pos)
  File "C:\Users\xxx\Downloads\xxx\Voice\uexp2awb.py", line 13, in copypart
    data = f1.read(chunk)
ValueError: read length must be non-negative or -1
```

able to send the file over if needed.

**Comment by maxwell-nc** [comment]
this file is not suitable for this script, no closing tags.
the file suffix is uexp,but the contents may be different, this script only for some kind of awb music uexp.
you can try umodel or other tools.
